### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by pecasdev** [Querela/termux-usb-python#1]
Hey sorry to bother you on your repository but there's no other way to contact github users, I saw on other threads that you managed to setup a 1.5 inch oled rgb i2c module from Waveshare on your raspberry pi. I have the same module and am trying to get it to work but having issues. If you're free and can help, shoot me an email please: [REDACTED]

**Comment by Querela** [comment]
Hi, no problem. Please wait a few days because I'm slightly busy with work.
Essentially, I used the example code linked in the weaveshare wiki and followed their tutorial + a website about raspberry pi pins. I also used their own display driver (test code works well) to write my own animations.
I will take some photos for the pins.

**Comment by pecasdev** [comment]
Some of the libraries are outdated and unsupported, I can't get i2cdetect
to find the module, so I'm thinking maybe I wired it wrong? Sure send a pic
of the pin wiring whenever you can thanks.

**Comment by Querela** [comment]
https://www.waveshare.com/wiki/1.5inch_RGB_OLED_Module
- Demo Code Download (contains driver library + examples)
- User Manual
  - connection as described in manual, (page 7) bcm mode 23, 24, power ground were nearby on my rpi3b+
  - for pinout lookup use this: https://de.pinout.xyz/pinout/pin18_gpio24

https://www.waveshare.com/wiki/Libraries_Installation_for_RPi
- I installed wiringPi, and the Python libs, like RPi.GPIO, and bcm2835 c libs
- enabled the interfaces, like i2c, serial, spi with raspi-config

Photos still in work ... Will clean this up later but those were my references. I still have my setup readme on my rpi but it is still offline and stowed away.

**Comment by pecasdev** [comment]
Hey thanks for the response. In the time since we last spoke I managed to
get it to work, so it's all good now. Thank you for the help!

**Comment by Querela** [comment]
Ok, no problem. And congrats. :-)
Sorry, but I was/am still somewhat swamped with work...
Will close for now.
And will see about adding some easier direct contact options.
